server:
  port: 8083

spring:
  application:
    name: txlcn-c

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/txlcn-c?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: pwd888888
  redis:
    host: 192.168.252.131
    port: 6379
    password:
    database: 1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

tx-lcn:
  client:
    manager-address: localhost:8070

logging:
  level:
    root: info