server:
  port: 8082

spring:
  application:
    name: txlcn-b

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/txlcn-b?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: pwd888888
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

tx-lcn:
  client:
    manager-address: localhost:8070

logging:
  level:
    root: info